#:include Screens/EditPopup.kv


<Card>:
    Image:
        id: card_img
        source: ''
    MDLabel:
        id: card_name
        text: ''


<Screens>
    orientation: "vertical"
    pos_hint: {"top": .9}
    size_hint_y: .9


<MDLabel>
    size_hint_y: .1

<Image>
    size_hint_y: 1
    pos_hint: {'center_x': .5, 'top_y': .8}


<PopupContent>:
    orientation: 'vertical'
    size_hint_x: 1
    size_hint_y: None
    height: "300dp"

    MDSeparator:

<MDTextField>
    id: 'edit_year'
